Fix TypeError: multinomial() missing 1 required positional arguments: "num_samples" Fix RuntimeError: cudnn RNN backward can only be called in training mode